// backoffice/src/components/Alert.vue
<script setup>
import { ref, computed } from "vue";

const INFO = "info";
const ERROR = "error";

const alert = ref({
  type: undefined,
  message: undefined,
  visible: false,
  timeout: undefined,
});

const alertClass = computed(() => {
  const error = alert.value.type === ERROR;
  return {
    "alert-danger": error,
    "alert-success": !error,
  };
});

function error(message, duration = 5000) {
  clearTimeout(alert.value.timeout);
  alert.value = {
    type: ERROR,
    message,
    visible: true,
    timeout: setTimeout(() => {
      alert.value.visible = false;
    }, duration),
  };
}

function info(message, duration = 5000) {
  clearTimeout(alert.value.timeout);
  alert.value = {
    type: INFO,
    message,
    visible: true,
    timeout: setTimeout(() => {
      alert.value.visible = false;
    }, duration),
  };
}

defineExpose({ error, info });
</script>

<template>
  <div v-if="alert.visible" class="alert" :class="alertClass" role="alert">
    {{ alert.message }}
  </div>
</template>

// store/src/lib/components/Alert.svelte
<script>
  const INFO = "info";
  const ERROR = "error";

  let alert = {
    type: undefined,
    message: undefined,
    visible: false,
    timeout: undefined,
  };

  export function error(message, duration = 5000) {
    clearTimeout(alert.timeout);
    alert = {
      type: ERROR,
      message,
      visible: true,
      timeout: setTimeout(() => {
        alert.visible = false;
      }, duration),
    };
  }

  export function info(message, duration = 5000) {
    clearTimeout(alert.timeout);
    alert = {
      type: INFO,
      message,
      visible: true,
      timeout: setTimeout(() => {
        alert.visible = false;
      }, duration),
    };
  }
</script>

{#if alert.visible}
  <div
    class="alert"
    class:alert-danger={alert.type === ERROR}
    class:alert-success={alert.type === INFO}
    role="alert"
  >
    {alert.message}
    <slot />
  </div>
{/if}
